version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend.Dockerfile
    environment:
      - RUST_LOG=info
      - SECRET=1234567890123456789012345678901234567890123456789012345678901234
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - ADDR=0.0.0.0:8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - migrate
    networks:
      - todos

  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend.Dockerfile
      args:
        - BASE_URL=http://127.0.0.1:8080/api/v1
    environment:
      - PORT=3080
    ports:
      - 3080:3080

  migrate:
    build:
      context: ./
      dockerfile: ./docker/migrate.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - todos

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - todos

networks:
  todos:
    name: todos
