version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    environment:
      - RUST_LOG=debug
      - SECRET=1234567890123456789012345678901234567890123456789012345678901234
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - ADDR=0.0.0.0:8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - migrate
    networks:
      - todos

  migrate:
    build:
      context: ./backend
      dockerfile: ../docker/migrate.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - todos

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - todos

networks:
  todos:
    name: todos
